# Generated by Django 3.1.7 on 2021-03-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='images')),
                ('imageName', models.CharField(blank=True, max_length=30)),
                ('imageCaption', models.CharField(max_length=300)),
            ],
        ),
    ]
